pytest_httpserver/httpserver.py: make mypy compatible with werkzeug 3.0.0
In werkzeug 3.0.0 they removed the attributes which were previously
announced, but mypy complains about this, even if I add hasattr() check.

This is the error thrown by mypy:
```
pytest_httpserver/httpserver.py:139: error: Module has no attribute "parse_authorization_header"; maybe "parse_options_header"?
```

I tried with `assert` and `if`, both with getattr and hasattr checks but
none of these worked.